theme: rennes-hugo-theme
_merge: deep
params:
  home:
    head:
      title: both # both | page | site
  posts:
    index:
      layout: grid # grid | list
      options:
        summary: false
        image: false
    share_links:
      enabled: false
