#ECEDI INDEXER CONFIG
content_dirs:
  - /content/fr/pages
exclude_dirs:
  - /content/fr/pages/plan-du-site
has_thematic: false
taxonomies:
  - name : 'Catégories'
    field_name: 'category'
  - name: 'Formats'
    field_name: 'format'